Jeroen topic api
daoneandonly/backend-a2 pull request #28
Opened 2021-03-28 21:38 UTC by Jeroen777

I've added an API to load unsplash images on a page.
I've  used a new package for this called request

2021-03-28 21:52 UTC, daoneandonly requested changes
Very nice! Be sure to be careful with private informations such as API keys.

2021-03-28 21:52 UTC, daoneandonly commented on app.js
> +      request("https://api.unsplash.com/photos?client_id=RsyiavOTOKJ65Sgr3PECQZ97VYTWbzAwEbHAVoR62Oc", function (error, response, body){
Be careful with using private keys in the codebase. We can move this the `.env` file

2021-03-29 12:56 UTC, pepijnkok commented
Looks good to me now!

2021-03-29 13:29 UTC, daoneandonly approved these changes
For a real app, we would use a check or give an alternative to the api key. For a prototype like we're making, this would be fine. Good work 👍

2021-03-29 14:18 UTC, Jeroen777 commented
I've merged the develop branch in to my API branch. Was a small problem with an url of my function, but it is fixed now.

2021-03-29 14:23 UTC, merged